import BlockInfo from '@app/components/BlockInfo'
import BlockTable from '@app/components/BlockTable'
import EthPrice from '@app/components/EthPrice'
import TransactionsTable from '@app/components/TransactionsTable'
import { Container, GridItem, Grid, Box, Text } from '@chakra-ui/react'
import Head from 'next/head'
import Card from '../components/Card'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container maxW="container.xl" mx="auto" position="relative">
        <Box as="nav" zIndex={999} position="fixed" top="6" left={0} right={0} maxW="container.xl" mx="auto" px="4">
          <Box bg="whiteAlpha.50" backdropFilter="auto" backdropBlur="6px" p="4" rounded="lg">
            <Text fontWeight="bold" textAlign="center">
              Simple Etherscan
            </Text>
          </Box>
        </Box>

        <Grid templateColumns={{ base: 'repeat(1, 1fr)', md: 'repeat(6, 1fr)' }} w="full" gap={4} pt="24">
          <GridItem colSpan={{ base: 1, md: 2 }}>
            <EthPrice />
          </GridItem>
          <GridItem colSpan={{ base: 1, md: 4 }}>
            <BlockInfo />
          </GridItem>
          <GridItem colSpan={{ base: 1, md: 3 }} display="block">
            <Card title="Latest Block">
              <BlockTable />
            </Card>
          </GridItem>
          <GridItem colSpan={{ base: 1, md: 3 }} display="block">
            <Card title="Latest Transaction">
              <TransactionsTable />
            </Card>
          </GridItem>
        </Grid>

        <Box as="nav" my="4" p="4" bg="whiteAlpha.50" backdropFilter="auto" backdropBlur="6px" rounded="lg">
          <Text fontWeight="bold" textAlign="center" fontSize="sm">
            © {new Date().getFullYear()} by I Putu Saputrayana
          </Text>
        </Box>
      </Container>
    </>
  )
}
